@v1=http://localhost:8080/api/v1

### GET /test
GET {{v1}}/test

### GET /get-courses
GET {{v1}}/get-courses

### PUT /add-review/:id
PUT {{v1}}/add-review/66e4cd821ceca1bac93e891a
Content-Type: application/json
Accept: application/json

{
    "review": "It's cool",
    "rating": 5
}
 
### PUT /add-reply
PUT {{v1}}/add-reply
Content-Type: application/json
Accept: application/json

{
    "comment": "Thank you for you review",
    "courseId": "66e4cd821ceca1bac93e891a",
    "reviewId": "66e9ac283907c4a907252662"
}
